[package]
name = "demos"
version = "0.1.0"
edition = "2024"

[dependencies]
crazyflie-lib = { path = ".." }
crazyflie-link = "0.4.1"
futures = "0.3.31"
tokio = { version = "1.48.0", features = ["full"] }

